### example deployment configuration file
### scf-azure-values.yaml

env:
  # the FQDN of your domain  
  DOMAIN: autolb.example.com
  # the UAA prefix is required
  UAA_HOST: uaa.autolb.example.com
  UAA_PORT: 2793
  GARDEN_ROOTFS_DRIVER: "overlay-xfs"

kube:
  storage_class:
    persistent: "persistent"
    shared: "shared"

  registry:
    hostname: "registry.suse.com"
    username: ""
    password: ""
  organization: "cap"

secrets:
  # create very strong passwords, and protect them just as 
  # carefully as you would protect any root passwords
  CLUSTER_ADMIN_PASSWORD: password
  UAA_ADMIN_CLIENT_SECRET: password

services:
  loadbalanced: true